version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: filter # in prod, see docker secrets
  web:
    build: .
    command: bash /entrypoint.sh
    volumes:
      - .:/usr/src/panoramix
    ports:
      - "3000:3000"
    depends_on:
      - db
    # tty: true
    # d for deamon, launch in background
    # i for interactive, I can interact with the container console.
    # tty not be to it as deamon
    # docker-compose up -d => en tâche de fond mais rend la main dans la console.
    # docker-compose up => par défaut c'est tty

# docker-compose down -v => clean
# docker-compose up --build => create the image AND run docker-compose.yml
# docker-compose exec web bash
# ln -s /usr/bin/nodejs /usr/bin/node
# Damien Duportal damien.duportal@gmail.com